import AppKit
import Foundation

/// 설치된 게임마다 `~/Applications/<게임 이름>.app` 바로가기를 만들고,
/// 더 이상 설치되어 있지 않은 바로가기는 휴지통으로 보낸다.
enum ShortcutSync {
    /// 우리가 만든 번들임을 표시하는 Info.plist 키
    static let markerKey = "SteamShelfAppID"

    /// 건너뛴 이유. 문장이 아니라 사유만 들고 있다가 표시할 때 번역한다.
    enum SkipReason {
        case nameTaken
        case writeFailed(String)
        case trashFailed(String)
    }

    struct Skipped {
        let name: String
        let reason: SkipReason
    }

    struct Report {
        var created: [String] = []
        var updated: [String] = []
        var removed: [String] = []
        var skipped: [Skipped] = []

        var isEmpty: Bool {
            created.isEmpty && updated.isEmpty && removed.isEmpty && skipped.isEmpty
        }
    }

    static var applicationsDir: URL {
        let dir = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Applications")
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }

    // MARK: - 기존 바로가기 식별

    private struct ManagedBundle {
        let url: URL
        let appID: String
        let isOurs: Bool   // false면 Steam이 만든 autogenerated 바로가기
    }

    /// 우리가 만든 번들 + Steam이 "Add to Applications"로 만든 번들을 찾는다.
    /// 그 외 사용자의 일반 앱은 절대 건드리지 않는다.
    private static func managedBundles() -> [ManagedBundle] {
        let fm = FileManager.default
        guard let entries = try? fm.contentsOfDirectory(
            at: applicationsDir, includingPropertiesForKeys: nil) else { return [] }

        var result: [ManagedBundle] = []
        for entry in entries where entry.pathExtension == "app" {
            let plistURL = entry.appendingPathComponent("Contents/Info.plist")
            if let data = try? Data(contentsOf: plistURL),
               let plist = try? PropertyListSerialization.propertyList(
                    from: data, options: [], format: nil) as? [String: Any],
               let appID = plist[markerKey] as? String {
                result.append(ManagedBundle(url: entry, appID: appID, isOurs: true))
                continue
            }
            // Steam이 만든 바로가기: run.sh 안에 autogenerated 마커와 steam:// URL이 있다.
            let script = entry.appendingPathComponent("Contents/MacOS/run.sh")
            if let text = try? String(contentsOf: script, encoding: .utf8),
               text.contains("autogenerated file"),
               let appID = steamAppID(inScript: text) {
                result.append(ManagedBundle(url: entry, appID: appID, isOurs: false))
            }
        }
        return result
    }

    private static func steamAppID(inScript text: String) -> String? {
        for pattern in ["steam://rungameid/", "steam://run/"] {
            guard let range = text.range(of: pattern) else { continue }
            let digits = text[range.upperBound...].prefix { $0.isNumber }
            if !digits.isEmpty { return String(digits) }
        }
        return nil
    }

    // MARK: - 동기화

    static func sync(games: [Game]) -> Report {
        var report = Report()
        let fm = FileManager.default
        let existing = managedBundles()
        let installedIDs = Set(games.map(\.appID))

        // 1) 설치된 게임 → 번들 생성/갱신
        for game in games {
            let desiredName = bundleName(for: game.name)
            let desiredURL = applicationsDir.appendingPathComponent(desiredName)
            let previous = existing.first { $0.appID == game.appID }

            // 이름이 바뀌었거나 Steam이 만든 옛 번들이 있으면 정리한다.
            if let previous, previous.url.standardized != desiredURL.standardized {
                try? fm.trashItem(at: previous.url, resultingItemURL: nil)
            }

            let alreadyThere = fm.fileExists(atPath: desiredURL.path)
            if alreadyThere {
                let isManaged = existing.contains { $0.url.standardized == desiredURL.standardized }
                guard isManaged else {
                    report.skipped.append(Skipped(name: desiredName, reason: .nameTaken))
                    continue
                }
                try? fm.removeItem(at: desiredURL)
            }

            do {
                try writeBundle(for: game, at: desiredURL)
                if alreadyThere || previous != nil {
                    report.updated.append(game.name)
                } else {
                    report.created.append(game.name)
                }
            } catch {
                report.skipped.append(
                    Skipped(name: game.name, reason: .writeFailed(error.localizedDescription)))
            }
        }

        // 2) 설치되지 않은 게임의 바로가기 → 휴지통
        for bundle in existing where !installedIDs.contains(bundle.appID) {
            let name = bundle.url.deletingPathExtension().lastPathComponent
            do {
                try fm.trashItem(at: bundle.url, resultingItemURL: nil)
                report.removed.append(name)
            } catch {
                report.skipped.append(
                    Skipped(name: name, reason: .trashFailed(error.localizedDescription)))
            }
        }

        // Launch Services에 변경을 알린다.
        NSWorkspace.shared.noteFileSystemChanged(applicationsDir.path)
        return report
    }

    /// 파일 이름으로 못 쓰는 문자 정리
    static func bundleName(for gameName: String) -> String {
        var cleaned = gameName
            .replacingOccurrences(of: "/", with: "-")
            .replacingOccurrences(of: ":", with: " -")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        if cleaned.hasPrefix(".") { cleaned.removeFirst() }
        if cleaned.isEmpty { cleaned = "Steam Game" }
        return cleaned + ".app"
    }

    private static func writeBundle(for game: Game, at url: URL) throws {
        let fm = FileManager.default
        let macOS = url.appendingPathComponent("Contents/MacOS")
        let resources = url.appendingPathComponent("Contents/Resources")
        try fm.createDirectory(at: macOS, withIntermediateDirectories: true)
        try fm.createDirectory(at: resources, withIntermediateDirectories: true)

        // 실행 스크립트
        let script = """
        #!/bin/bash
        # Steam Shelf가 생성한 바로가기 — 직접 편집하지 마세요.
        open "steam://rungameid/\(game.appID)"
        """
        let scriptURL = macOS.appendingPathComponent("run.sh")
        try script.write(to: scriptURL, atomically: true, encoding: .utf8)
        try fm.setAttributes([.posixPermissions: 0o755], ofItemAtPath: scriptURL.path)

        // 아이콘 (실패해도 바로가기 자체는 동작한다)
        let hasIcon = Artwork.writeICNS(
            appID: game.appID,
            to: resources.appendingPathComponent("icon.icns")
        )

        var plist: [String: Any] = [
            "CFBundleExecutable": "run.sh",
            "CFBundleIdentifier": "com.steamshelf.game.\(game.appID)",
            "CFBundleName": game.name,
            "CFBundleDisplayName": game.name,
            "CFBundleInfoDictionaryVersion": "6.0",
            "CFBundlePackageType": "APPL",
            "CFBundleShortVersionString": "1.0",
            "CFBundleVersion": "1.0",
            "LSApplicationCategoryType": "public.app-category.games",
            "NSHighResolutionCapable": true,
            markerKey: game.appID,
        ]
        if hasIcon { plist["CFBundleIconFile"] = "icon.icns" }

        let data = try PropertyListSerialization.data(
            fromPropertyList: plist, format: .xml, options: 0)
        try data.write(to: url.appendingPathComponent("Contents/Info.plist"))

        // 아이콘 캐시를 확실히 갱신시키기 위해 수정 시각을 건드린다.
        try? fm.setAttributes([.modificationDate: Date()], ofItemAtPath: url.path)
    }
}
